# Generated by Django 4.2.16 on 2025-07-16 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wkz", "0010_sport_mapping_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="user",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="sport",
            name="user",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="activity",
            name="sport",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="wkz.sport", verbose_name="Sport"
            ),
        ),
        migrations.AlterField(
            model_name="settings",
            name="path_to_trace_dir",
            field=models.CharField(
                default="/Users/bfordham/.wkz/tracks", max_length=200, verbose_name="Path to Traces Directory"
            ),
        ),
        migrations.AlterField(
            model_name="sport",
            name="mapping_name",
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name="Mapping Name"),
        ),
        migrations.AlterField(
            model_name="sport",
            name="name",
            field=models.CharField(max_length=24, verbose_name="Sport Name"),
        ),
        migrations.AlterField(
            model_name="sport",
            name="slug",
            field=models.SlugField(blank=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name="sport",
            unique_together={("user", "name")},
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "path_to_trace_dir",
                    models.CharField(
                        default="/Users/bfordham/.wkz/tracks", max_length=200, verbose_name="Path to Traces Directory"
                    ),
                ),
                (
                    "path_to_garmin_device",
                    models.CharField(blank=True, default="", max_length=200, verbose_name="Path to Garmin Device"),
                ),
                (
                    "number_of_days",
                    models.IntegerField(
                        choices=[
                            (9999, "all"),
                            (1095, "3 years"),
                            (730, "2 years"),
                            (365, "1 year"),
                            (180, "180 days"),
                            (90, "90 days"),
                            (30, "30 days"),
                            (10, "10 days"),
                        ],
                        default=30,
                    ),
                ),
                (
                    "delete_files_after_import",
                    models.BooleanField(default=False, verbose_name="Delete fit Files after Copying "),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("user", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
