# Generated by Django 4.2.16 on 2025-07-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wkz", "0011_activity_user_sport_user_alter_activity_sport_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="public_profile",
            field=models.BooleanField(
                default=False,
                help_text="Allow others to view your activities at /users/<username>",
                verbose_name="Make Profile Public",
            ),
        ),
    ]
