# Generated by Django 4.2.16 on 2025-07-16 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wkz", "0013_alter_activity_options_activity_achievement_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sport",
            name="category",
            field=models.CharField(
                blank=True,
                help_text="e.g., 'Cardio', 'Strength', 'Flexibility', 'Sports', 'Water'",
                max_length=50,
                null=True,
                verbose_name="Category",
            ),
        ),
        migrations.AddField(
            model_name="sport",
            name="external_mappings",
            field=models.TextField(
                blank=True,
                help_text="JSON mapping of external service activity types",
                null=True,
                verbose_name="External Mappings",
            ),
        ),
        migrations.AddField(
            model_name="sport",
            name="has_distance",
            field=models.BooleanField(
                default=True,
                help_text="Whether this sport typically tracks distance",
                verbose_name="Distance-based Activity",
            ),
        ),
        migrations.AddField(
            model_name="sport",
            name="is_system_sport",
            field=models.BooleanField(
                default=False, help_text="Created by system, available to all users", verbose_name="System Sport"
            ),
        ),
        migrations.AlterField(
            model_name="sport",
            name="icon",
            field=models.CharField(max_length=50, verbose_name="Icon"),
        ),
        migrations.AlterField(
            model_name="sport",
            name="mapping_name",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Mapping Name"),
        ),
        migrations.AlterField(
            model_name="sport",
            name="name",
            field=models.CharField(max_length=50, verbose_name="Sport Name"),
        ),
    ]
