# Generated by Django 4.2.16 on 2025-07-16 17:24

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wkz", "0014_sport_category_sport_external_mappings_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetricTile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100, verbose_name="Tile Name")),
                (
                    "key",
                    models.CharField(
                        help_text="Unique identifier for this tile (e.g., 'total_distance')",
                        max_length=50,
                        unique=True,
                        verbose_name="Tile Key",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Display Title")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Description")),
                (
                    "icon",
                    models.CharField(
                        help_text="FontAwesome class (e.g., 'fa-road', 'fa-stopwatch')",
                        max_length=50,
                        verbose_name="FontAwesome Icon Class",
                    ),
                ),
                (
                    "color",
                    colorfield.fields.ColorField(
                        default="#42FF71", image_field=None, max_length=18, samples=None, verbose_name="Icon Color"
                    ),
                ),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("total", "Total (Sum)"),
                            ("average", "Average"),
                            ("count", "Count"),
                            ("max", "Maximum"),
                            ("min", "Minimum"),
                            ("trend", "Trend (7-day)"),
                            ("custom", "Custom Calculation"),
                        ],
                        max_length=50,
                        verbose_name="Metric Type",
                    ),
                ),
                (
                    "data_field",
                    models.CharField(
                        help_text="Field name from Activity or Traces model (e.g., 'distance', 'duration')",
                        max_length=100,
                        verbose_name="Data Field",
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        blank=True,
                        help_text="Display unit (e.g., 'km', 'hours', 'kcal')",
                        max_length=20,
                        null=True,
                        verbose_name="Unit",
                    ),
                ),
                (
                    "format_type",
                    models.CharField(
                        choices=[
                            ("number", "Number"),
                            ("decimal", "Decimal"),
                            ("duration", "Duration"),
                            ("date", "Date"),
                            ("custom", "Custom Format"),
                        ],
                        default="number",
                        max_length=20,
                        verbose_name="Format Type",
                    ),
                ),
                ("decimal_places", models.IntegerField(default=0, verbose_name="Decimal Places")),
                (
                    "applicable_to",
                    models.CharField(
                        choices=[
                            ("all", "All Activities"),
                            ("sport", "Specific Sports"),
                            ("category", "Sport Categories"),
                        ],
                        default="all",
                        max_length=20,
                        verbose_name="Applicable To",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Metric Tile",
                "verbose_name_plural": "Metric Tiles",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SportTileConfiguration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "tiles_per_row",
                    models.IntegerField(
                        default=4, help_text="Number of tiles to display per row", verbose_name="Tiles per Row"
                    ),
                ),
                (
                    "applies_to",
                    models.CharField(
                        choices=[
                            ("dashboard", "Dashboard"),
                            ("sport_page", "Sport Page"),
                            ("public_profile", "Public Profile"),
                            ("all", "All Views"),
                        ],
                        default="all",
                        max_length=20,
                        verbose_name="Applies To",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "sport",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="wkz.sport", verbose_name="Sport"),
                ),
            ],
            options={
                "verbose_name": "Sport Tile Configuration",
                "verbose_name_plural": "Sport Tile Configurations",
            },
        ),
        migrations.CreateModel(
            name="SportTileOrder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("order", models.IntegerField(default=0, verbose_name="Display Order")),
                (
                    "custom_title",
                    models.CharField(
                        blank=True,
                        help_text="Override the default tile title",
                        max_length=100,
                        null=True,
                        verbose_name="Custom Title",
                    ),
                ),
                (
                    "custom_color",
                    colorfield.fields.ColorField(
                        blank=True,
                        default=None,
                        help_text="Override the default tile color",
                        image_field=None,
                        max_length=18,
                        null=True,
                        samples=None,
                        verbose_name="Custom Color",
                    ),
                ),
                ("is_visible", models.BooleanField(default=True, verbose_name="Visible")),
                (
                    "sport_config",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="wkz.sporttileconfiguration"),
                ),
                ("tile", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="wkz.metrictile")),
            ],
            options={
                "verbose_name": "Sport Tile Order",
                "verbose_name_plural": "Sport Tile Orders",
                "ordering": ["order"],
                "unique_together": {("sport_config", "tile")},
            },
        ),
        migrations.AddField(
            model_name="sporttileconfiguration",
            name="tiles",
            field=models.ManyToManyField(through="wkz.SportTileOrder", to="wkz.metrictile", verbose_name="Tiles"),
        ),
        migrations.AddField(
            model_name="sporttileconfiguration",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Leave blank for global configuration",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sporttileconfiguration",
            unique_together={("sport", "user", "applies_to")},
        ),
    ]
